name: Deploy Melodi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      # Clone Repo
      - uses: actions/checkout@v3    

      - name: Generate SSH Key
        run: echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key

      - name: Test Ansible Version
        run: ansible -i aws_ec2.yml --private-key=ansible_key -m ping all -u ec2-user
