name: Deploy Melodi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clone Repo
      - uses: actions/checkout@v3

      - name: Check files
        run: ls

      - name: Test Ansible Version
        run: ansible --version 
